Admin.create email: 'admin@gmail.com', password: 'password'

Product.create(name: "Cheese", category: "Classic", description: "double layer of mozzarella")
Product.create(name: "NY Classic", category: "Classic", description: "pepperoni")
Product.create(name: "Pepp & Mushroom", category: "Classic", description: "pepperoni & button mushrooms")
Product.create(name: "Manhattan", category: "Classic", description: "ham, pepperoni, italian sausage, ground beef, alami & bacon")
Product.create(name: "Garden Special", category: "Classic", description: "fresh tomatoes, black olives, mushrooms, onions, red & green bell peppers")
Product.create(name: "Hawaiian", category: "Classic", description: "ham, pineapple & bacon")
Product.create(name: "New York's Finest", category: "Classic", description: "italian sausage, ham, pepperoni, bacon,, ground beef, black olives, mushrooms, onions, red & green bell peppers")
Product.create(name: "Tribeca Mushroom", category: "Specialty Pizza", description: "shiitake, button & oyster mushroom")
Product.create(name: "Anchovy Lovers", category: "Specialty Pizza", description: "black olives, anchovies, capers, roasted garlic, mushroom & onions")
Product.create(name: "4 Cheese", category: "Specialty Pizza", description: "cheese heaven! mozzarella, cheddar, fontina & feta")
Product.create(name: "Corona Chicken", category: "Specialty Pizza", description: "tangy strips of chicken with Southwestern Salsa")
Product.create(name: "Gourmet Garden", category: "Specialty Pizza",  description: "zucchini, grilled eggplant, fresh tomatoes, black olives, capers, mushrooms, onions, red & green bell peppers")
Product.create(name: "Roasted Garlic", category: "Specialty Pizza", description: "shrimp, onions, roasted garlic in wine butter sauce")
Product.create(name: "Four Seasons", category: "Specialty Pizza",  description: "gourmet sampler: NY Classic, #4 Cheese, Anchovy Lovers, Roasted Garlic & shrimp")


Variant.create(product_id: 1, size: "10 in", price: 175)
Variant.create(product_id: 1, size: "14 in", price: 285)
Variant.create(product_id: 1, size: "18 in", price: 440)
Variant.create(product_id: 2, size: "10 in", price: 210)
Variant.create(product_id: 2, size: "14 in", price: 340)
Variant.create(product_id: 2, size: "18 in", price: 530)
Variant.create(product_id: 3, size: "10 in", price: 220)
Variant.create(product_id: 3, size: "14 in", price: 250)
Variant.create(product_id: 3, size: "18 in", price: 540)
Variant.create(product_id: 4, size: "10 in", price: 250)
Variant.create(product_id: 4, size: "14 in", price: 295)
Variant.create(product_id: 4, size: "18 in", price: 565)
Variant.create(product_id: 5, size: "10 in", price: 210)
Variant.create(product_id: 5, size: "14 in", price: 340)
Variant.create(product_id: 5, size: "18 in", price: 530)
Variant.create(product_id: 6, size: "10 in", price: 210)
Variant.create(product_id: 6, size: "14 in", price: 340)
Variant.create(product_id: 6, size: "18 in", price: 530)
Variant.create(product_id: 7, size: "10 in", price: 260)
Variant.create(product_id: 7, size: "14 in", price: 420)
Variant.create(product_id: 7, size: "18 in", price: 575)
Variant.create(product_id: 8, size: "10 in", price: 260)
Variant.create(product_id: 8, size: "14 in", price: 390)
Variant.create(product_id: 8, size: "18 in", price: 560)
Variant.create(product_id: 9, size: "10 in", price: 275)
Variant.create(product_id: 9, size: "14 in", price: 450)
Variant.create(product_id: 9, size: "18 in", price: 595)
Variant.create(product_id: 10, size: "10 in", price: 250)
Variant.create(product_id: 10, size: "14 in", price: 400)
Variant.create(product_id: 10, size: "18 in", price: 560)
Variant.create(product_id: 11, size: "10 in", price: 250)
Variant.create(product_id: 11, size: "14 in", price: 420)
Variant.create(product_id: 11, size: "18 in", price: 575)
Variant.create(product_id: 12, size: "10 in", price: 250)
Variant.create(product_id: 12, size: "14 in", price: 410)
Variant.create(product_id: 12, size: "18 in", price: 585)
Variant.create(product_id: 13, size: "10 in", price: 240)
Variant.create(product_id: 13, size: "14 in", price: 405)
Variant.create(product_id: 13, size: "18 in", price: 505)
Variant.create(product_id: 14, size: "10 in", price: 240)
Variant.create(product_id: 14, size: "14 in", price: 430)
Variant.create(product_id: 14, size: "18 in", price: 590)