Product.create(name: "Cheese", category: "Classic")
Product.create(name: "NY Classic", category: "Classic")
Product.create(name: "Pepp & Mushroom", category: "Classic")
Product.create(name: "Manhattan", category: "Classic")
Product.create(name: "Garden Special", category: "Classic")
Product.create(name: "Hawaiian", category: "Classic")
Product.create(name: "New York's Finest", category: "Classic")
Product.create(name: "Tribeca Mushroom", category: "Specialty Pizza")
Product.create(name: "Anchovy Lovers", category: "Specialty Pizza")
Product.create(name: "4 Cheese", category: "Specialty Pizza")
Product.create(name: "Corona Chicken", category: "Specialty Pizza")
Product.create(name: "Gourmet Garden", category: "Specialty Pizza")
Product.create(name: "Roasted Garlic", category: "Specialty Pizza")
Product.create(name: "Four Seasons", category: "Specialty Pizza")

Variant.create(product_id: 1, size: "10 in", price: 175)
Variant.create(product_id: 1, size: "14 in", price: 285)
Variant.create(product_id: 1, size: "18 in", price: 440)
Variant.create(product_id: 2, size: "10 in", price: 210)
Variant.create(product_id: 2, size: "14 in", price: 340)
Variant.create(product_id: 2, size: "18 in", price: 530)
Variant.create(product_id: 3, size: "10 in", price: 220)
Variant.create(product_id: 3, size: "14 in", price: 250)
Variant.create(product_id: 3, size: "18 in", price: 540)
Variant.create(product_id: 4, size: "10 in", price: 250)
Variant.create(product_id: 4, size: "14 in", price: 295)
Variant.create(product_id: 4, size: "18 in", price: 565)
Variant.create(product_id: 5, size: "10 in", price: 210)
Variant.create(product_id: 5, size: "14 in", price: 340)
Variant.create(product_id: 5, size: "18 in", price: 530)
Variant.create(product_id: 6, size: "10 in", price: 210)
Variant.create(product_id: 6, size: "14 in", price: 340)
Variant.create(product_id: 6, size: "18 in", price: 530)
Variant.create(product_id: 7, size: "10 in", price: 260)
Variant.create(product_id: 7, size: "14 in", price: 420)
Variant.create(product_id: 7, size: "18 in", price: 575)
Variant.create(product_id: 8, size: "10 in", price: 260)
Variant.create(product_id: 8, size: "14 in", price: 390)
Variant.create(product_id: 8, size: "18 in", price: 560)
Variant.create(product_id: 9, size: "10 in", price: 275)
Variant.create(product_id: 9, size: "14 in", price: 450)
Variant.create(product_id: 9, size: "18 in", price: 595)
Variant.create(product_id: 10, size: "10 in", price: 250)
Variant.create(product_id: 10, size: "14 in", price: 400)
Variant.create(product_id: 10, size: "18 in", price: 560)
Variant.create(product_id: 11, size: "10 in", price: 250)
Variant.create(product_id: 11, size: "14 in", price: 420)
Variant.create(product_id: 11, size: "18 in", price: 575)
Variant.create(product_id: 12, size: "10 in", price: 250)
Variant.create(product_id: 12, size: "14 in", price: 410)
Variant.create(product_id: 12, size: "18 in", price: 585)
Variant.create(product_id: 13, size: "10 in", price: 240)
Variant.create(product_id: 13, size: "14 in", price: 405)
Variant.create(product_id: 13, size: "18 in", price: 505)
Variant.create(product_id: 14, size: "10 in", price: 240)
Variant.create(product_id: 14, size: "14 in", price: 430)
Variant.create(product_id: 14, size: "18 in", price: 590)